### ISSUE TITLE
The problem with a new interlocutor.

### ISSUE THREAD

**Issue by Gorfar** [vdrhtc/concrypt#2]
If someone new (who hasn't had a conversation with me before or I have just deleted it) write a message, a problem can be seen in the attached file. He doesn't have an avatar and name.
![chats](https://cloud.githubusercontent.com/assets/4509284/11896542/6af7cda0-a598-11e5-89e3-f60999e78189.png)

**Comment by Gorfar** [comment]
To be honest, the program has hung after this. :(

**Comment by vdrhtc** [comment]
Thanks
Fixed in eea8dc7
